# Generated by Django 2.1.2 on 2018-10-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product', max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('picture', models.ImageField(height_field=100, upload_to='where are we putting these', width_field=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Enter email address', max_length=254)),
                ('password', models.CharField(help_text='Enter password', max_length=40)),
                ('name', models.CharField(help_text='Full name', max_length=20)),
                ('rating', models.IntegerField()),
                ('profile_picture', models.ImageField(height_field=100, upload_to='where are we putting these', width_field=100)),
            ],
        ),
    ]
