# Generated by Django 2.1.2 on 2018-10-24 20:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('umarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Some Category', help_text='Category', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_rating',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='userID',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
