# Generated by Django 2.1.2 on 2018-10-24 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('umarket', '0002_auto_20181024_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productID',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='userID',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
