# Generated by Django 2.1.1 on 2018-11-03 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Description of the course', max_length=500)),
                ('starRating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('averageGrade', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(help_text='Enter your review for this class', max_length=500)),
                ('starRating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('gradeReceived', models.DecimalField(decimal_places=1, max_digits=2)),
                ('date', models.DateField(blank=True, null=True)),
                ('tags', models.CharField(help_text='Describe course difficulty as easy/medium/hard/fun/boring/netural', max_length=10)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SUBJECT', max_length=40)),
                ('abbreviation', models.CharField(default='COURSE', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=500)),
                ('courses', models.ManyToManyField(to='classdoor.Course')),
                ('subjectsOffered', models.ManyToManyField(blank=True, to='classdoor.Subject')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('major', models.ManyToManyField(to='classdoor.Subject')),
                ('writtenReviews', models.ManyToManyField(blank=True, to='classdoor.Review')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='universityName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='classdoor.University'),
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(help_text='Select a user for this review', null=True, on_delete=django.db.models.deletion.SET_NULL, to='classdoor.User'),
        ),
        migrations.AddField(
            model_name='course',
            name='reviews',
            field=models.ManyToManyField(help_text='Select a review for this class', to='classdoor.Review'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classdoor.Subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classdoor.Teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='university_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classdoor.University'),
        ),
    ]
