# Generated by Django 2.1.1 on 2018-10-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='ClassDesc',
        ),
    ]
