# Generated by Django 2.1.1 on 2018-11-05 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='courseOfReview',
            field=models.ForeignKey(help_text='Select a course for this description', null=True, on_delete=django.db.models.deletion.SET_NULL, to='classdoor.Course'),
        ),
    ]
