# Generated by Django 2.1.3 on 2018-11-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0002_review_courseofreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='reviews',
            field=models.ManyToManyField(blank=True, help_text='Select a review for this class', to='classdoor.Review'),
        ),
    ]
