# Generated by Django 2.1.1 on 2018-10-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0003_classdesc_avggrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdesc',
            name='preReqs',
            field=models.ManyToManyField(help_text='Select a preReq for this class', related_name='_classdesc_preReqs_+', to='classdoor.ClassDesc'),
        ),
        migrations.AlterField(
            model_name='classdesc',
            name='avgGrade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classdesc',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
