# Generated by Django 2.1.1 on 2018-11-15 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0004_auto_20181115_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdooruser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
