# Generated by Django 2.1.1 on 2018-10-19 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0005_auto_20181018_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=500)),
                ('starRating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('gradeReceived', models.DecimalField(decimal_places=2, max_digits=3)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('major', models.ManyToManyField(to='classdoor.Subject')),
                ('writtenReviews', models.ManyToManyField(to='classdoor.Review')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.AlterField(
            model_name='classdesc',
            name='avgGrade',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='classdesc',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='university',
            name='classes',
            field=models.ManyToManyField(to='classdoor.ClassDesc'),
        ),
        migrations.AddField(
            model_name='university',
            name='subjectsOffered',
            field=models.ManyToManyField(to='classdoor.Subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='universityName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='classdoor.University'),
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(help_text='Select a user for this review', null=True, on_delete=django.db.models.deletion.SET_NULL, to='classdoor.User'),
        ),
        migrations.AddField(
            model_name='review',
            name='classDesc',
            field=models.ForeignKey(help_text='Select a class for this description', null=True, on_delete=django.db.models.deletion.SET_NULL, to='classdoor.ClassDesc'),
        ),
        migrations.AddField(
            model_name='classdesc',
            name='reviews',
            field=models.ManyToManyField(help_text='Reviews for this class', to='classdoor.Review'),
        ),
        migrations.AddField(
            model_name='classdesc',
            name='subject',
            field=models.ForeignKey(help_text='Select a subject for this class', null=True, on_delete=django.db.models.deletion.SET_NULL, to='classdoor.Subject'),
        ),
        migrations.AddField(
            model_name='classdesc',
            name='universityName',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classdoor.University'),
        ),
    ]
