# Generated by Django 2.1.1 on 2018-11-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0005_auto_20181115_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdooruser',
            name='profileImage',
            field=models.CharField(default='profile-1.gif', max_length=15),
        ),
    ]
