# Generated by Django 2.1.1 on 2018-10-23 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0006_auto_20181018_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classdesc',
            old_name='avgGrade',
            new_name='grade',
        ),
        migrations.AddField(
            model_name='classdesc',
            name='date_of_review',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classdesc',
            name='description',
            field=models.CharField(help_text='Description of the course', max_length=200),
        ),
        migrations.AlterField(
            model_name='classdesc',
            name='preReqs',
            field=models.ManyToManyField(blank=True, help_text='PreReqs for this class', related_name='_classdesc_preReqs_+', to='classdoor.ClassDesc'),
        ),
        migrations.RemoveField(
            model_name='classdesc',
            name='reviews',
        ),
        migrations.AddField(
            model_name='classdesc',
            name='reviews',
            field=models.ForeignKey(help_text='Review for this class', max_length=500, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classdoor.Review'),
        ),
        migrations.AlterField(
            model_name='university',
            name='subjectsOffered',
            field=models.ManyToManyField(blank=True, to='classdoor.Subject'),
        ),
        migrations.AlterField(
            model_name='user',
            name='writtenReviews',
            field=models.ManyToManyField(blank=True, to='classdoor.Review'),
        ),
    ]
