# Generated by Django 2.1.1 on 2018-11-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0007_classdooruser_reviewswritten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classdooruser',
            name='reviewsWritten',
        ),
        migrations.AddField(
            model_name='classdooruser',
            name='reviewsWritten',
            field=models.ManyToManyField(null=True, to='classdoor.Review'),
        ),
    ]
