# Generated by Django 2.1.1 on 2018-10-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0007_auto_20181023_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classdesc',
            name='date_of_review',
        ),
        migrations.RemoveField(
            model_name='classdesc',
            name='reviews',
        ),
        migrations.AddField(
            model_name='classdesc',
            name='reviews',
            field=models.ManyToManyField(blank=True, help_text='Review for this class', to='classdoor.Review'),
        ),
    ]
