# Generated by Django 2.1.1 on 2018-10-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0008_auto_20181023_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='subjectsOffered',
            new_name='subjects',
        ),
        migrations.RemoveField(
            model_name='classdesc',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='classdesc',
            name='rating',
        ),
        migrations.AddField(
            model_name='classdesc',
            name='averageGrade',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='classdesc',
            name='starRating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='abbreviation',
            field=models.CharField(default='SUBJ', max_length=4),
        ),
        migrations.AlterField(
            model_name='review',
            name='gradeReceived',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='starRating',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
