# Generated by Django 2.1.1 on 2018-11-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0008_auto_20181116_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdooruser',
            name='reviewsWritten',
            field=models.ManyToManyField(to='classdoor.Review'),
        ),
    ]
