# Generated by Django 2.1.1 on 2018-11-03 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0009_auto_20181023_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Description of the course', max_length=500)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.RemoveField(
            model_name='classdesc',
            name='preReqs',
        ),
        migrations.RemoveField(
            model_name='classdesc',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='classdesc',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='classdesc',
            name='universityName',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='subjects',
            new_name='subjectsOffered',
        ),
        migrations.RemoveField(
            model_name='review',
            name='classDesc',
        ),
        migrations.RemoveField(
            model_name='review',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='abbreviation',
        ),
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.CharField(default=3, help_text='Describe course difficulty as easy/medium/hard/fun/boring/netural', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='gradeReceived',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='starRating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(help_text='Enter your review for this class', max_length=500),
        ),
        migrations.AlterField(
            model_name='university',
            name='classes',
            field=models.ManyToManyField(to='classdoor.Class'),
        ),
        migrations.DeleteModel(
            name='ClassDesc',
        ),
        migrations.AddField(
            model_name='class',
            name='review',
            field=models.ManyToManyField(help_text='Select a review for this class', to='classdoor.Review'),
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classdoor.Subject'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classdoor.Teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='university_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classdoor.University'),
        ),
    ]
