# Generated by Django 2.1.1 on 2018-11-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0011_auto_20181103_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='abbreviation',
            field=models.CharField(default='COURSE', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(default='SUBJECT', max_length=40),
        ),
    ]
