# Generated by Django 2.1.1 on 2018-11-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0012_auto_20181103_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='averageGrade',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
