# Generated by Django 2.1.1 on 2018-11-03 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0013_course_averagegrade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='rating',
            new_name='starRating',
        ),
    ]
