# Generated by Django 2.1.1 on 2018-11-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0014_auto_20181103_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='averageGrade',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='starRating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
