# Generated by Django 2.1.1 on 2018-11-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0015_auto_20181103_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='review',
            new_name='reviews',
        ),
    ]
