# Generated by Django 2.0 on 2018-10-21 18:13

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cast', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the movie', max_length=1000)),
                ('duration', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('genre', django_mysql.models.ListTextField(models.CharField(max_length=10), size=100)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=300)),
                ('date', models.DateField(blank=True, null=True)),
                ('number_people', models.IntegerField()),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Flick.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('bio', models.CharField(max_length=300)),
                ('pic', models.ImageField(blank=True, default='pic_folder/None/no-img.jpg', null=True, upload_to='picpath/')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Flick.User'),
        ),
        migrations.AddField(
            model_name='match',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Flick.Request'),
        ),
        migrations.AddField(
            model_name='match',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Flick.User'),
        ),
    ]
