# Generated by Django 2.1.1 on 2018-11-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_name', models.CharField(help_text='Enter a genre for the song (e.g. Swedish Heavy Metal)', max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
