# Generated by Django 2.1.1 on 2018-11-04 02:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HiveList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular Song across entire site', primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('song_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular Song across entire site', primary_key=True, serialize=False)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HiveList.Artist')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HiveList.Genre')),
            ],
        ),
    ]
