# Generated by Django 2.1.1 on 2018-11-04 02:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HiveList', '0002_artist_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('contributor_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular contributor', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular Playlist across entire site', primary_key=True, serialize=False)),
                ('playlist_name', models.CharField(help_text='Enter a title for the playlist (e.g. Meat Bird Execution Playlist)', max_length=200)),
                ('playlist_creation_date', models.DateField(auto_now_add=True)),
                ('playlist_description', models.TextField(help_text='Enter description for playlist', max_length=1000)),
                ('playlist_vote_time', models.DateTimeField(blank=True, default='2018-11-04 02:55')),
                ('playlist_ranking', models.IntegerField(default=0)),
                ('playlist_votingthreshold', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('playlist_is_private', models.BooleanField(default=False)),
                ('playlist_creator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HiveList.Contributor')),
            ],
        ),
        migrations.AddField(
            model_name='contributor',
            name='playlist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HiveList.Playlist'),
        ),
    ]
