# Generated by Django 2.1.1 on 2018-11-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiveList', '0008_auto_20181104_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_vote_time',
            field=models.DateTimeField(blank=True, default='2018-11-04 03:27'),
        ),
    ]
