# Generated by Django 2.1.1 on 2018-11-04 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HiveList', '0011_auto_20181104_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_vote_time',
        ),
    ]
