# Generated by Django 2.1.1 on 2018-11-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiveList', '0013_songinstance_voteinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinstance',
            name='number_no_votes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='songinstance',
            name='number_yes_votes',
            field=models.IntegerField(),
        ),
    ]
