# Generated by Django 2.1.1 on 2018-11-04 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HiveList', '0014_auto_20181104_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songinstance',
            name='number_no_votes',
        ),
        migrations.RemoveField(
            model_name='songinstance',
            name='number_yes_votes',
        ),
    ]
