# Generated by Django 2.1.1 on 2018-11-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiveList', '0015_auto_20181104_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='songinstance',
            name='number_no_votes',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='songinstance',
            name='number_yes_votes',
            field=models.IntegerField(default=None),
        ),
    ]
