# Generated by Django 2.1.1 on 2018-11-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HiveList', '0016_auto_20181104_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songinstance',
            name='contributor_id',
        ),
        migrations.RemoveField(
            model_name='songinstance',
            name='playlist_id',
        ),
        migrations.RemoveField(
            model_name='songinstance',
            name='song_id',
        ),
        migrations.RemoveField(
            model_name='voteinstance',
            name='contributor_id',
        ),
        migrations.RemoveField(
            model_name='voteinstance',
            name='playlist_id',
        ),
        migrations.RemoveField(
            model_name='voteinstance',
            name='song_id',
        ),
        migrations.DeleteModel(
            name='SongInstance',
        ),
        migrations.DeleteModel(
            name='VoteInstance',
        ),
    ]
