# Generated by Django 2.1.1 on 2018-11-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HiveList', '0020_voteinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='playlist_id',
        ),
    ]
