# Generated by Django 2.1.3 on 2018-11-05 22:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HiveList', '0023_auto_20181105_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this particular Song across entire site', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this particular Playlist across entire site', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this particular Song across entire site', primary_key=True, serialize=False),
        ),
    ]
