# Generated by Django 2.1.2 on 2018-11-06 07:58

import carton.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter class name', max_length=100)),
                ('code', models.CharField(help_text='Enter alphanumeric class code', max_length=15)),
                ('rating', models.IntegerField()),
                ('prereqs', models.ManyToManyField(blank=True, related_name='_course_prereqs_+', to='carton.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter instructor name', max_length=50)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_seats', models.IntegerField()),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, help_text='Enter when the class starts')),
                ('end_time', models.DateTimeField(default=carton.models.get_future, help_text='Enter when the class ends')),
                ('dow', models.CharField(help_text='Enter days of the week', max_length=5, null=True, verbose_name='')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carton.Course')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carton.Instructor')),
            ],
        ),
    ]
