# Generated by Django 2.1.1 on 2018-11-04 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='cur_class',
        ),
        migrations.AddField(
            model_name='session',
            name='d',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carton.Course'),
        ),
    ]
