# Generated by Django 2.1.2 on 2018-11-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0002_remove_course_prereqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prereqs',
            field=models.ManyToManyField(null=True, related_name='_course_prereqs_+', to='carton.Course'),
        ),
    ]
