# Generated by Django 2.1.1 on 2018-11-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0002_auto_20181104_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prereqs',
            field=models.ManyToManyField(blank=True, related_name='_course_prereqs_+', to='carton.Course'),
        ),
    ]
