# Generated by Django 2.1.2 on 2018-11-06 08:12

import carton.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0002_auto_20181106_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(default=carton.models.get_future, help_text='Enter when the class ends'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Enter when the class starts'),
        ),
    ]
