# Generated by Django 2.1.1 on 2018-11-04 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0003_auto_20181104_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='d',
            new_name='course',
        ),
    ]
