# Generated by Django 2.1.3 on 2018-11-25 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0004_auto_20181125_0357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'permissions': (('can_create_instructor', 'Can Create Instructor'),)},
        ),
    ]
