# Generated by Django 2.1.3 on 2018-11-05 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0004_auto_20181104_1916'),
        ('carton', '0003_course_prereqs'),
    ]

    operations = [
    ]
