# Generated by Django 2.1.3 on 2018-11-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0005_merge_20181105_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prereqs',
            field=models.ManyToManyField(blank=True, related_name='_course_prereqs_+', to='carton.Course'),
        ),
    ]
