# Generated by Django 2.1.3 on 2018-11-26 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0005_auto_20181126_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={},
        ),
    ]
