# Generated by Django 2.1.3 on 2018-11-26 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0006_auto_20181126_0044'),
        ('carton', '0005_auto_20181125_2012'),
    ]

    operations = [
    ]
