# Generated by Django 2.1.2 on 2018-11-05 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0006_auto_20181105_0237'),
        ('carton', '0006_auto_20181105_1616'),
    ]

    operations = [
    ]
