# Generated by Django 2.1.3 on 2018-11-05 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0006_auto_20181105_1616'),
        ('carton', '0006_auto_20181105_0237'),
    ]

    operations = [
    ]
