# Generated by Django 2.1.2 on 2018-11-05 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0007_merge_20181105_2124'),
        ('carton', '0007_merge_20181105_2217'),
    ]

    operations = [
    ]
