# Generated by Django 2.1.3 on 2018-11-26 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0007_merge_20181126_0418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={},
        ),
    ]
