# Generated by Django 2.1.2 on 2018-11-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0008_auto_20181126_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='courses_dooted',
            field=models.ManyToManyField(related_name='dooted', to='carton.Course'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='courses_past',
            field=models.ManyToManyField(related_name='past', to='carton.Course'),
        ),
    ]
