# Generated by Django 2.1.3 on 2018-11-06 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0007_merge_20181105_2129'),
        ('carton', '0008_merge_20181105_2247'),
    ]

    operations = [
    ]
