# Generated by Django 2.1.3 on 2018-11-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0009_merge_20181106_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('comment_text', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
