# Generated by Django 2.1.2 on 2018-11-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0010_auto_20181126_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='user_first_name', help_text='Your first name', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='user_last_name', help_text='Your last name', max_length=50),
        ),
    ]
