# Generated by Django 2.1.2 on 2018-11-27 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0012_auto_20181127_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='courses_downdooted',
            new_name='downdooted',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='courses_updooted',
            new_name='updooted',
        ),
    ]
