# Generated by Django 2.1.2 on 2018-11-29 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0014_auto_20181129_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
    ]
