# Generated by Django 2.1.2 on 2018-11-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0015_remove_course_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.IntegerField(default=4),
        ),
    ]
