# Generated by Django 2.1.2 on 2018-11-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0016_course_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='doots',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='updoots',
            field=models.IntegerField(null=True),
        ),
    ]
