# Generated by Django 2.1.2 on 2018-11-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0017_auto_20181129_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='doots',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='updoots',
            field=models.IntegerField(default=0),
        ),
    ]
