# Generated by Django 2.1.2 on 2018-12-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0018_auto_20181129_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='updoots',
            field=models.IntegerField(default=1),
        ),
    ]
