# Generated by Django 2.1.2 on 2018-11-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_movie_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture_url',
            field=models.CharField(default='https://test.jpg', max_length=300),
        ),
    ]
