# Generated by Django 2.1.2 on 2018-11-12 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_user_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Movie'),
        ),
    ]
