# Generated by Django 2.1.2 on 2018-11-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_match_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_id',
            field=models.BigIntegerField(default=111111),
        ),
    ]
