# Generated by Django 2.1.2 on 2018-12-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20181128_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='request',
            name='last_name',
        ),
        migrations.AddField(
            model_name='request',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
