# Generated by Django 2.1.2 on 2018-12-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20181202_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='username',
        ),
        migrations.AddField(
            model_name='match',
            name='usernames',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
