# Generated by Django 2.1.2 on 2018-12-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20181202_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
