# Generated by Django 2.1.2 on 2018-12-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_request_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture_url',
            field=models.CharField(default='https://res.cloudinary.com/dbgclcola/image/upload/v1541982429/profilepic.jpg', max_length=300),
        ),
    ]
