# Generated by Django 2.1.2 on 2018-11-13 18:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, help_text='Please be as specific as possible. Include the building and room number if applicable. A kind reminder, it is best to meet in public places.', max_length=30, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('datetime', models.DateTimeField()),
                ('capacity', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='event_images')),
                ('duration', models.DurationField(default=datetime.timedelta(0, 3600))),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pet_type', models.CharField(max_length=30)),
                ('breed', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('image', models.ImageField(null=True, upload_to='pet_images')),
            ],
        ),
        migrations.CreateModel(
            name='PetUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('location', models.CharField(blank=True, help_text='Your area of residence', max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('image', models.ImageField(null=True, upload_to='user_images')),
                ('hosting', models.ManyToManyField(to='Catch.Event')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Catch.PetUser'),
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Catch.PetUser'),
        ),
        migrations.AddField(
            model_name='event',
            name='pet',
            field=models.ManyToManyField(to='Catch.Pet'),
        ),
    ]
