# Generated by Django 2.1.2 on 2018-10-21 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.CharField(max_length=30)),
                ('location', models.FloatField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('breed', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=3000)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catch.Image')),
            ],
        ),
        migrations.CreateModel(
            name='PetUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('location', models.FloatField(max_length=50)),
                ('description', models.CharField(max_length=3000)),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Catch.PetUser'),
        ),
        migrations.AddField(
            model_name='event',
            name='pet_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Catch.PetUser'),
        ),
    ]
