# Generated by Django 2.1.2 on 2018-10-31 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
