# Generated by Django 2.1.2 on 2018-10-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petuser',
            name='firstname',
            field=models.CharField(default='aaa', max_length=30),
            preserve_default=False,
        ),
    ]
