# Generated by Django 2.1.2 on 2018-10-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catch', '0002_auto_20181031_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='petuser',
            name='hosting',
            field=models.ManyToManyField(to='Catch.Event'),
        ),
    ]
