# Generated by Django 2.1.2 on 2018-10-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catch', '0002_petuser_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
    ]
