# Generated by Django 2.1.2 on 2018-11-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catch', '0002_auto_20181122_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
