# Generated by Django 2.0.6 on 2018-10-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catch', '0004_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=40)),
                ('event_description', models.CharField(max_length=40)),
                ('event_capacity', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
