# Generated by Django 2.1.2 on 2018-10-25 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catch', '0005_auto_20181025_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petuser',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 3600)),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ManyToManyField(to='Catch.Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='Please be as specific as possible. Include the building and room number if applicable. A kind reminder, it is best to meet in public places.', max_length=30, null=True),
        ),
        migrations.RemoveField(
            model_name='event',
            name='pet',
        ),
        migrations.AddField(
            model_name='event',
            name='pet',
            field=models.ManyToManyField(to='Catch.Pet'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.RemoveField(
            model_name='pet',
            name='image',
        ),
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ManyToManyField(to='Catch.Image'),
        ),
        migrations.AlterField(
            model_name='petuser',
            name='description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='petuser',
            name='location',
            field=models.CharField(blank=True, help_text='Your area of residence', max_length=100, null=True),
        ),
    ]
