# Generated by Django 2.1.1 on 2018-10-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catch', '0005_auto_20181006_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_pettype',
            field=models.CharField(default='qwe', max_length=40),
            preserve_default=False,
        ),
    ]
