# Generated by Django 2.0.6 on 2018-10-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catch', '0005_auto_20181025_1434'),
        ('Catch', '0006_auto_20181025_1845'),
    ]

    operations = [
    ]
