# Generated by Django 2.0.6 on 2018-10-08 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catch', '0006_events_event_pettype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_pettype',
        ),
    ]
