# Generated by Django 2.0.6 on 2018-10-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catch', '0007_merge_20181025_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='Please be as specific as possible. Include the building and room number if applicable. A kind reminder, it is best to meet in public places.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='petuser',
            name='location',
            field=models.CharField(blank=True, help_text='Your area of residence', max_length=100, null=True),
        ),
    ]
