# Generated by Django 2.0.6 on 2018-10-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catch', '0007_remove_events_event_pettype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=40)),
                ('pet_age', models.CharField(max_length=40)),
                ('pet_description', models.CharField(max_length=400)),
                ('pet_breed', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='event_description',
            field=models.CharField(max_length=400),
        ),
    ]
