# Generated by Django 2.1.2 on 2018-10-27 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catch', '0008_auto_20181025_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='image',
        ),
    ]
