# Generated by Django 2.1.2 on 2018-10-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catch', '0009_auto_20181027_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='qweqw', max_length=30),
            preserve_default=False,
        ),
    ]
